### PR TITLE
Switch to NpmClientHandler

### PR DESCRIPTION
**Pull request by rchl**

### CODE REVIEW

**Comment by jfcherng** [comment]
```
Traceback (most recent call last):
  File "C:\Users\Clover\AppData\Roaming\Sublime Text\Packages\sublime_lib\st3\sublime_lib\resource_path.py", line 521, in read_bytes
    return sublime.load_binary_resource(str(self))
  File "C:\Program Files\Sublime Text\Lib\python33\sublime.py", line 247, in load_binary_resource
    raise IOError('resource "%s" not found' % name)
OSError: resource "Packages/LSP-bash/bash-language-server" not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files\Sublime Text\Lib\python33\sublime_plugin.py", line 478, in on_api_ready
    plc()
  File "C:\Users\Clover\AppData\Roaming\Sublime Text\Installed Packages\LSP-bash.sublime-package\plugin.py", line 6, in plugin_loaded
    LspBashPlugin.setup()
  File "C:\Users\Clover\AppData\Roaming\Sublime Text\Packages\lsp_utils\st3\lsp_utils\npm_client_handler.py", line 61, in setup
    cls.__server.setup()
  File "C:\Users\Clover\AppData\Roaming\Sublime Text\Packages\lsp_utils\st3\lsp_utils\server_npm_resource.py", line 68, in setup
    self._copy_to_cache()
  File "C:\Users\Clover\AppData\Roaming\Sublime Text\Packages\lsp_utils\st3\lsp_utils\server_npm_resource.py", line 92, in _copy_to_cache
    ResourcePath(src_path).copytree(cache_server_path, exist_ok=True)
  File "C:\Users\Clover\AppData\Roaming\Sublime Text\Packages\sublime_lib\st3\sublime_lib\resource_path.py", line 608, in copytree
    resource.copy(file_path)
  File "C:\Users\Clover\AppData\Roaming\Sublime Text\Packages\sublime_lib\st3\sublime_lib\resource_path.py", line 582, in copy
    data = self.read_bytes()
  File "C:\Users\Clover\AppData\Roaming\Sublime Text\Packages\sublime_lib\st3\sublime_lib\resource_path.py", line 523, in read_bytes
    raise FileNotFoundError(str(self)) from err
FileNotFoundError: Packages/LSP-bash/bash-language-server
```

---

```
>>> sublime.load_binary_resource('Packages/LSP-bash/bash-language-server')
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Sublime Text\Lib\python38\sublime.py", line 247, in load_binary_resource
    raise FileNotFoundError(f'resource "{name}" not found')
FileNotFoundError: resource "Packages/LSP-bash/bash-language-server" not found
```

**Comment by rchl** [comment]
It clearly worked before or nobody would be able to install the server. Stange. :)

**Comment by jfcherng** [comment]
Or maybe I somehow test it in a wrong way since I do it all manually with downloaded zip files.

**Comment by rchl** [comment]
Something must be wrong with the way you are testing yes.
BTW. When manually trying `sublime.load_binary_resource('Packages/LSP-bash/bash-language-server')` you need to switch to Python3.3 host (right click in console input field).

**Comment by rchl** [comment]
Actually `load_resource` doesn't work with directories but `sublime_lib` does so this should work:
```py
sublime.load_binary_resource('Packages/LSP-bash/bash-language-server')
```

**Comment by jfcherng** [comment]
At this moment, 

- if I test it like there is a `.no-sublime-package`, it installed.
- if I test it with a manually packed `.sublime-package`, it failed to installed.

**Comment by jfcherng** [comment]
Nvm. Things are all good. 

Somehow the package created by `Package Control: Create Package File` works.
While the one I manually zipped and change ext to `.sublime-package` does not. :confused: 

I have no problem with this PR now.

**Comment by rchl** [comment]
Cool. I also wasn't able to make my manually zipped package to work. So strange. :)

**Pull request merged**
